# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install
        uses: CultureHQ/actions-yarn@master
        with:
          args: install

      - name: Build
        uses: CultureHQ/actions-yarn@master
        with:
          args: build

      - name: Setup sshpass
        run: sudo apt-get install sshpass

      - name: Deploy
        uses: garygrossgarten/github-action-scp@release
        with:
            local: dist
            remote: /data/web/setzhao/dist
            host: ${{ secrets.HOST }}
            username: root
            password: ${{ secrets.PASSWORD }}
            concurrency: 20
            rmRemote: true
